name: 'bsky-bot'

on:
  push:
    branches:
      - development
      - 'feature/**'

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.13.1
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.1'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install autopep8 and flake8
        run: |
          pip install autopep8 flake8

      - name: Automatically fix code style with autopep8
        run: |
          autopep8 --in-place --aggressive src/*.py tests/*.py

      - name: Lint Python code with flake8
        run: |
          flake8 .

      - name: Run tests with pytest
        run: |
          pip install pytest
          pytest --maxfail=1 --disable-warnings -q
